export { default as About } from "./About/About";
export { default as Articulo } from "./Blog/Articulo";
export { default as ContainerBlog } from "./Blog/ContainerBlog";
export { default as Hero } from "./Hero/Hero";
export { default as Home } from "./Home/Home";
export { default as ContainerRoad } from "./RoadMap/ContainerRoad";
export { default as Hito } from "./RoadMap/Hito";
export { default as RoadMap } from "./RoadMap/RoadMap";
export { default as Store } from "./Store/Store";
export * from "./VideoCalling/API";
export { default as VideoCalling } from "./VideoCalling/VideoCalling";
export { default as Login } from "./Login/Login";
